"""Tests for genomic-vcf-filtering.

The agent applies the same four-stage filter cascade (region restriction,
biallelic-SNV restriction, MAF >= 0.01, |AFR_AF - EAS_AF| >= 0.10) to each of
three 1000 Genomes Project Phase 3 V5b slices, writing per-slice output:

    /root/output/<slice_id>/filtered.vcf.gz       (compressed, indexed)
    /root/output/<slice_id>/filtered.vcf.gz.tbi
    /root/output/<slice_id>/summary.json

Ground truth was generated by the reference oracle (solution/solve.sh) and is
deterministic: any correct implementation of the same filter cascade applied
in any equivalent order will reproduce it byte-for-byte. Per-slice expected
counts and variant-key sets live in /tests/expected.json.

Test structure (1 + 7 * 3 = 22 distinct outcome checks):
  1) test_output_directory_exists                          (1)
  2) test_filtered_vcf_exists_and_indexed[slice]           (3)
  3) test_filtered_vcf_parseable[slice]                    (3)
  4) test_summary_json_parseable_with_required_fields[slice]  (3)
  5) test_variant_count_matches_oracle[slice]              (3)
  6) test_variant_keys_match_oracle[slice]                 (3)
  7) test_all_variants_in_required_region[slice]           (3)
  8) test_all_variants_are_biallelic_snv[slice]            (3)
"""
from __future__ import annotations

import gzip
import json
from pathlib import Path

import pytest

OUTPUT_ROOT = Path("/root/output")
EXPECTED_PATH = Path("/tests/expected.json")
MANIFEST_PATH = Path("/root/data/slices.json")


def _load_expected() -> dict:
    return json.loads(EXPECTED_PATH.read_text(encoding="utf-8"))


def _load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


EXPECTED = _load_expected()
MANIFEST = _load_manifest() if MANIFEST_PATH.exists() else {"slices": []}
SLICE_IDS = sorted(EXPECTED.keys())


def _slice_dir(slice_id: str) -> Path:
    return OUTPUT_ROOT / slice_id


def _filtered_vcf(slice_id: str) -> Path:
    return _slice_dir(slice_id) / "filtered.vcf.gz"


def _summary_path(slice_id: str) -> Path:
    return _slice_dir(slice_id) / "summary.json"


def _read_vcf_records(path: Path) -> list[tuple[str, int, str, str]]:
    """Return list of (CHROM, POS, REF, ALT) for each non-header line."""
    out = []
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt") as f:
        for line in f:
            if line.startswith("#"):
                continue
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 5:
                continue
            out.append((cols[0], int(cols[1]), cols[3], cols[4]))
    return out


def _parse_region(region: str) -> tuple[str, int, int]:
    chrom, rest = region.split(":")
    start, end = rest.split("-")
    return chrom, int(start), int(end)


# ------------------------------------------------------------------

def test_output_directory_exists():
    assert OUTPUT_ROOT.is_dir(), f"{OUTPUT_ROOT} does not exist"


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_filtered_vcf_exists_and_indexed(slice_id: str):
    vcf = _filtered_vcf(slice_id)
    tbi = vcf.with_suffix(vcf.suffix + ".tbi")
    assert vcf.is_file(), f"{vcf} not found"
    assert tbi.is_file(), (
        f"{tbi} not found — the filtered VCF for {slice_id} must carry a tabix index"
    )


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_filtered_vcf_parseable(slice_id: str):
    vcf = _filtered_vcf(slice_id)
    if not vcf.is_file():
        pytest.fail(f"{slice_id}: filtered.vcf.gz missing")
    try:
        records = _read_vcf_records(vcf)
    except (OSError, gzip.BadGzipFile) as e:
        pytest.fail(f"{slice_id}: filtered.vcf.gz did not parse as gzipped VCF: {e}")
    assert records, f"{slice_id}: filtered.vcf.gz contains no variant records"


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_summary_json_parseable_with_required_fields(slice_id: str):
    path = _summary_path(slice_id)
    assert path.is_file(), f"{path} not found"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        pytest.fail(f"{slice_id}: summary.json did not parse: {e}")
    for f in ("slice_id", "variant_count", "variant_keys", "region"):
        assert f in data, f"{slice_id}: summary.json missing required field {f!r}"
    assert data["slice_id"] == slice_id
    assert isinstance(data["variant_count"], int)
    assert isinstance(data["variant_keys"], list)
    assert all(isinstance(k, str) for k in data["variant_keys"])
    assert isinstance(data["region"], str)


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_variant_count_matches_oracle(slice_id: str):
    path = _summary_path(slice_id)
    if not path.is_file():
        pytest.fail(f"{slice_id}: summary.json missing")
    data = json.loads(path.read_text(encoding="utf-8"))
    expected = EXPECTED[slice_id]
    actual = data.get("variant_count")
    assert actual == expected["variant_count"], (
        f"{slice_id}: variant_count = {actual}; expected {expected['variant_count']}. "
        f"Off by {abs(actual - expected['variant_count'])} — "
        f"likely a filter-cascade ordering or polarity error."
    )


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_variant_keys_match_oracle(slice_id: str):
    path = _summary_path(slice_id)
    if not path.is_file():
        pytest.fail(f"{slice_id}: summary.json missing")
    data = json.loads(path.read_text(encoding="utf-8"))
    expected = EXPECTED[slice_id]
    actual_keys = sorted(data.get("variant_keys", []))
    expected_keys = sorted(expected["variant_keys"])
    if actual_keys == expected_keys:
        return
    only_actual = set(actual_keys) - set(expected_keys)
    only_expected = set(expected_keys) - set(actual_keys)
    msg = []
    if only_expected:
        sample = sorted(only_expected)[:3]
        msg.append(
            f"{slice_id}: {len(only_expected)} variant(s) missing from agent output. "
            f"First missing: {sample}"
        )
    if only_actual:
        sample = sorted(only_actual)[:3]
        msg.append(
            f"{slice_id}: {len(only_actual)} variant(s) extra in agent output. "
            f"First extra: {sample}"
        )
    pytest.fail("; ".join(msg))


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_all_variants_in_required_region(slice_id: str):
    vcf = _filtered_vcf(slice_id)
    if not vcf.is_file():
        pytest.fail(f"{slice_id}: filtered.vcf.gz missing")
    expected_region = EXPECTED[slice_id]["region"]
    chrom, start, end = _parse_region(expected_region)
    records = _read_vcf_records(vcf)
    out_of_region = [
        (c, p, r, a) for c, p, r, a in records
        if c != chrom or p < start or p > end
    ]
    assert not out_of_region, (
        f"{slice_id}: {len(out_of_region)} variant(s) are outside {expected_region}. "
        f"First: {out_of_region[0]}"
    )


_BASES = set("ACGT")


@pytest.mark.parametrize("slice_id", SLICE_IDS)
def test_all_variants_are_biallelic_snv(slice_id: str):
    vcf = _filtered_vcf(slice_id)
    if not vcf.is_file():
        pytest.fail(f"{slice_id}: filtered.vcf.gz missing")
    records = _read_vcf_records(vcf)
    bad = []
    for chrom, pos, ref, alt in records:
        if "," in alt:
            bad.append(("multi-allelic", chrom, pos, ref, alt))
        elif len(ref) != 1 or len(alt) != 1:
            bad.append(("indel/MNP", chrom, pos, ref, alt))
        elif ref.upper() not in _BASES or alt.upper() not in _BASES:
            bad.append(("non-ACGT base", chrom, pos, ref, alt))
    assert not bad, (
        f"{slice_id}: {len(bad)} variant(s) violate biallelic-SNV restriction. "
        f"First: {bad[0]}"
    )
